spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ams?useUnicode=true&characterEncoding=utf-8&ServerTimezone=Asia/Shanghai
    username: root
    password: root

server:
  port: 8081

logging:
  level:
    com.tqq.csmall.passport: trace