spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
  profiles:
    active: dev

knife4j:
  enable: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml