spring:
  datasource:
    url: jdbc:mysql://project.003456.com:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&ServerTimezone=Asia/Shanghai
    username: fsihsdid
    password: hsuiacvh

server:
  port: 443

logging:
  level:
    com.tqq.csmall.product: warn