spring:
  datasource:
    url: jdbc:mysql://10.10.10.10:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&ServerTimezone=Asia/Shanghai
    username: test
    password: testproject

server:
  port: 8080

logging:
  level:
    com.tqq.csmall.product: trace