spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&ServerTimezone=Asia/Shanghai
    username: root
    password: root

server:
  port: 8080

logging:
  level:
    com.tqq.csmall.product: info
csmall:
  jwt:
    secret-key: afdvdsbvdfbfddgfrfsafsaf23rff23r3